name: EAS Build

on:
  pull_request:
    types:
      - labeled

jobs:
  build-android:
    if: contains(github.event.pull_request.labels.*.name, 'eas-build-android')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build on EAS
        run: eas build --platform android --profile preview-android --non-interactive

  build-ios:
    if: contains(github.event.pull_request.labels.*.name, 'eas-build-ios')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build on EAS
        run: eas build --platform ios --profile preview-ios --non-interactive
